apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myprecious-johnny
  namespace: aa-johnny
spec:
  chart:
    spec:
      chart: ./charts/myprecious
      version: 0.1.x
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1 # keep trying to remediate  
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate    
  releaseName: johnny
  valuesFrom:
  - kind: ConfigMap
    name: aa-johnny-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
    optional: false
